fieldLayouts:
  b633a8b6-b091-4a9b-b155-612993b14dfe:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e8c28a80-2947-427d-abc2-9f34fb5eb804
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 78dd93ac-acdd-4b70-a6de-a7a48aa24238 # Photo Image
            instructions: 'Selection to show on this page'
            label: 'Image Selections'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a6e4f39-d5db-4976-8549-93ee2c66222e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 11b46838-b2ab-4657-b0ea-45eb39ded7c8
        userCondition: null
handle: feature
hasTitleField: true
name: Feature
section: 3c3877e5-d9a3-4d31-af5c-b62f193298d8 # Feature
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
