fieldLayouts:
  d83e0ed0-de29-4bf4-8f44-260a41e7ed6c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5b498121-89ea-450e-a96f-f13b70015ff1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 27070d73-4653-4322-ad6a-54124377725b
        userCondition: null
fs: general
handle: general
name: General
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
