columnSuffix: osdmgqkd
contentColumnType: string(7)
fieldGroup: 827245d1-6f19-4823-92e3-10d57c2c31ac # Global Fields
handle: background
instructions: null
name: Background
searchable: false
settings:
  defaultColor: '#e8aa75'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
