defaultPlacement: end
enableVersioning: true
handle: contact
name: Contact
propagationMethod: all
siteSettings:
  9e983e3d-f7b6-40bc-9b32-e5d8f980dd57: # zeus
    enabledByDefault: true
    hasUrls: true
    template: contact/_entry
    uriFormat: contact
type: single
