defaultPlacement: beginning
enableVersioning: true
handle: feature
name: Feature
propagationMethod: all
siteSettings:
  9e983e3d-f7b6-40bc-9b32-e5d8f980dd57: # zeus
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
